version: '3'

services:
  ts-site-dev:
    environment:
      - DEBUG=true
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../source:/app
    ports:
      - "3000:3000"
