version: '3'

services:
  ts-site-dev:
    environment:
      - DEBUG=true
    env_file: 
      - ./../.env.dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
    ports:
      - "5000:5000"
