FROM node:alpine

WORKDIR /app

ENV PORT=5000

RUN apk update && \
    apk upgrade && \
    apk add npm

COPY ./../source/package*.json /app

RUN npm install --save react react-dom react-scripts
RUN npm install axios
RUN npm install node-sass

RUN npm install

COPY ./../source /app

CMD ["npm", "start"]
