"""Remove tasks.testing_mode

Revision ID: 9a0f4f6b8413
Revises: b328b9892829
Create Date: 2023-12-09 15:02:04.995879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0f4f6b8413'
down_revision: Union[str, None] = 'b328b9892829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'testing_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('testing_mode', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
