"""Add tasks.correct_output|correct|incorrect_log

Revision ID: b328b9892829
Revises: 541129cddab6
Create Date: 2023-12-09 14:56:12.726880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b328b9892829'
down_revision: Union[str, None] = '541129cddab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('correct_output', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('correct', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('incorrect_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'incorrect_log')
    op.drop_column('tasks', 'correct')
    op.drop_column('tasks', 'correct_output')
    # ### end Alembic commands ###
