"""add tasks.extra_params

Revision ID: d8ae369ec3bd
Revises: 9a0f4f6b8413
Create Date: 2023-12-09 16:30:49.322068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ae369ec3bd'
down_revision: Union[str, None] = '9a0f4f6b8413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('extra_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_params')
    # ### end Alembic commands ###
