version: '3'

services:
  ts-frontend-dev:
    environment:
      - DEBUG=true
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../source:/app
    ports:
      - "5000:5000"
