FROM node:19.6.0-alpine3.17

ENV NODE_ENV development
WORKDIR /app 

COPY package.json yarn.lock ./
RUN yarn install --development
COPY ./node_modules ./

COPY ./public ./src ./nginx.conf ./
EXPOSE 3000

# CMD [ "echo", "$(yarn bin)" ]
# CMD [ "ls", "-la" ]
CMD [ "yarn", "start" ]
