version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    env_file:
      - ./.env
    environment:
      - DB_PORT=5000
    command: 
      - -p 5000
    volumes:
      - postgres_dev_data:/var/lib/postgres/data
    ports:
      - 5000:5000
    restart: unless-stopped

  backend:
    depends_on:
      - postgres
    hostname: backend
    environment:
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5000
    env_file: 
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    hostname: frontend
    ports:
      - 3000:5002

  nginx:
    depends_on:
      - frontend
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80

volumes:
  postgres_dev_data:

networks:
  postgres:
    driver: bridge