version: '3.4'

services:
  scylla_db:
    image: scylladb/scylla
    hostname: scylla_db
    container_name: scylla_db
    restart: always
    command: --api-address 0.0.0.0 --overprovisioned 1
    volumes:
      - ./data/scylla:/var/lib/scylla
    ports:
      - 9042:9042
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9160:9160
      - 9180:9180
      - 10000:10000
    networks:
      - scylla
    
  backend-dev:
    depends_on:
      - postgres
    hostname: backend
    environment:
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5000
    env_file: 
      - ./.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    networks:
      - postgres
      - nginx
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
    
  # frontend-dev:
  #   depends_on:
  #     - backend-dev
  #   hostname: frontend
  #   env_file: 
  #     - ./.env.dev
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   networks:
  #     - scylla
  #     - nginx
  #   ports:
  #     - 5002:5002
  #     - 24678:24678
  #   volumes:
  #     - ./frontend:/app

  # nginx:
  #   depends_on:
  #     - backend-dev
  #     - frontend-dev
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   networks:
  #     - nginx
  #   ports:
  #     - 80:80

networks:
  scylla:
    driver: bridge
  nginx:
    driver: bridge
