version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DB_PORT: 5000
      PGDATA: /data/postgres
    command: 
      - -p 5000
    volumes:
      - /opt/xiver/projects_data/edu/db/data:/data/postgres
      - /opt/xiver/projects_data/edu/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres

  backend:
    depends_on:
      - postgres
    hostname: backend
    environment:
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5000
    env_file: 
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - postgres
      - nginx
    ports:
      - 5001:5001

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    hostname: frontend
    networks:
      - nginx
    ports:
      - 3000:5002

  nginx:
    depends_on:
      - frontend
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks:
      - nginx
    ports:
      - 83:80
      - 84:443
  
  service-test:
    image: alpine
    depends_on:
      - nginx
      - frontend
      - backend
      - postgres
    command: sleep 20s

networks:
  postgres:
    driver: bridge
  nginx:
    driver: bridge
