FROM node:19.6.0-alpine3.17

ENV NODE_ENV development
WORKDIR /app 

COPY node_modules /app/

COPY ./public ./src ./nginx.conf ./
EXPOSE 3000

# CMD [ "echo", "$(yarn bin)" ]
# CMD [ "ls", "-la" ]
CMD [ "yarn", "start" ]
