version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    env_file:
      - ./.env.dev
    environment:
      - DB_PORT=5000
    command: 
      - -p 5000
    volumes:
      - postgres_dev_data:/var/lib/postgres/data
    ports:
      - 5000:5432
    restart: unless-stopped

  backend-dev:
    depends_on:
      - postgres
    hostname: backend
    environment:
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5000
    env_file: 
      - ./.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app

  frontend-dev:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    hostname: frontend
    ports:
      - 3000:80

  nginx:
    depends_on:
      - frontend-dev
      - backend-dev
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80

volumes:
  postgres_dev_data:

networks:
  postgres:
    driver: bridge