[tool.poetry]
name = "Testing system API"
version = "0.1.0"
description = "Testing system`s API [By Xiver organization]."
authors = [
    "GigantPro <pochtagigantpro@gmail.com>"
]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.94.1"
uvicorn = "^0.21.1"
sqlalchemy = "^2.0.6"
psycopg2-binary = "^2.9.5"
fastapi-users = {extras = ["scylla-driver"], version = "^12.1.2"}
asyncpg = "^0.27.0"
loguru = "^0.7.0"
scylla-driver = "^3.26.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.2"
pytest = "^7.2.2"
mypy = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]
max-line-length = 120
disable = [
    "C0114",
    "C0115",
    "C0116",
    "C0201",
    "R0903",
    "W0511",
    "R0912",
    "E0213",
    "E1102",
    "E1136",
    "E0402",
    "W0622",
    "W0105",
    "C0207",
    "C2801",
    "C0206",
    "C0200",
    "E0401",
    "W1401",
    "W0212",
    "C0103",
    "E0611",
    "W0223",
    "R0901",
    "W0613",
    "R1719",
    "R0902"
]
