version: '3'

services:
  discord-bot:
    environment:
      - DEBUG=false
    env_file: 
      - ./../.env
    build:
      context: /opt/xiver/testing-system
      dockerfile: docker/Dockerfile
    volumes:
      - /var/log/xiver/testing-system:/app/log
    ports:
      - "5000:5000"
