FROM python:3.11-alpine3.17 as python-base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && \
    apk upgrade

RUN apk add --update docker openrc
RUN rc-update add docker boot

WORKDIR /app

COPY solution.py solution.py

CMD ["python", "solution.py"]
