"""Change relationship at course 2

Revision ID: 01e2b3252d0c
Revises: 23751ef0f75e
Create Date: 2023-11-28 20:17:44.828320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e2b3252d0c'
down_revision: Union[str, None] = '23751ef0f75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
