"""Change relationship at course 2

Revision ID: 040546519cf1
Revises: 375f88c94634
Create Date: 2023-11-28 21:56:32.046702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040546519cf1'
down_revision: Union[str, None] = '375f88c94634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_course_data_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'course_data_id')
    op.add_column('courses_data', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses_data', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses_data', type_='foreignkey')
    op.drop_column('courses_data', 'course_id')
    op.add_column('courses', sa.Column('course_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_course_data_id_fkey', 'courses', 'courses_data', ['course_data_id'], ['id'])
    # ### end Alembic commands ###
