"""Add changed_time to all tables

Revision ID: 09cb55e25bd4
Revises: 800860e0c202
Create Date: 2023-12-03 17:53:49.839880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09cb55e25bd4'
down_revision: Union[str, None] = '800860e0c202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classinvites', sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('classrooms', sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('classrooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('courses', sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('lessons', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('lessons', sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'changed_time')
    op.drop_column('lessons', 'changed_time')
    op.drop_column('lessons', 'created_at')
    op.drop_column('courses', 'changed_time')
    op.alter_column('classrooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('classrooms', 'changed_time')
    op.drop_column('classinvites', 'changed_time')
    # ### end Alembic commands ###
