"""Add course_data_id to module

Revision ID: 1973bad0fbd5
Revises: 66cf5f2f89bc
Create Date: 2023-12-03 22:06:56.934234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1973bad0fbd5'
down_revision: Union[str, None] = '66cf5f2f89bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('modules', sa.Column('course_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'modules', 'courses_data', ['course_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'course_data_id')
    op.drop_column('modules', 'course_id')
    # ### end Alembic commands ###
