"""Change relationship at course 2

Revision ID: 23751ef0f75e
Revises: 56fb94495dd4
Create Date: 2023-11-28 20:16:19.720364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23751ef0f75e'
down_revision: Union[str, None] = '56fb94495dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'courses_data', ['course_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'course_data_id')
    # ### end Alembic commands ###
