"""Create simple_solutions

Revision ID: 42643050c080
Revises: 0bc1aeea3c4d
Create Date: 2023-12-11 20:08:36.755311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42643050c080'
down_revision: Union[str, None] = '0bc1aeea3c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_solutions')
    # ### end Alembic commands ###
