"""Add title & description to modules

Revision ID: 60c7c58583b4
Revises: a2ef219e75f1
Create Date: 2023-11-13 22:14:40.941552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c7c58583b4'
down_revision: Union[str, None] = 'a2ef219e75f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('title', sa.String(), nullable=False))
    op.add_column('modules', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'description')
    op.drop_column('modules', 'title')
    # ### end Alembic commands ###
