"""Change relationship at course 2

Revision ID: 643c7185b8ec
Revises: 01e2b3252d0c
Create Date: 2023-11-28 20:21:06.074800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643c7185b8ec'
down_revision: Union[str, None] = '01e2b3252d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
