"""Add course_id to module

Revision ID: 66cf5f2f89bc
Revises: f4e87ca1a376
Create Date: 2023-12-03 22:03:01.830396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cf5f2f89bc'
down_revision: Union[str, None] = 'f4e87ca1a376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'course_id')
    # ### end Alembic commands ###
