"""Add solutions.tests_ids

Revision ID: 6ae9ea487697
Revises: b074ca6fff7e
Create Date: 2023-12-13 20:04:49.072533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae9ea487697'
down_revision: Union[str, None] = 'b074ca6fff7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('tests_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'tests_ids')
    # ### end Alembic commands ###
