"""Update tasks && create solution

Revision ID: 6fd9190f21c5
Revises: a48002c35df6
Create Date: 2023-12-09 21:35:56.156203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd9190f21c5'
down_revision: Union[str, None] = 'a48002c35df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('extra_params', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'extra_params')
    # ### end Alembic commands ###
