"""Remove relationship and set forgein key

Revision ID: 800860e0c202
Revises: d92ce850eeb0
Create Date: 2023-12-02 21:54:07.283636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800860e0c202'
down_revision: Union[str, None] = 'd92ce850eeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'courses_data', ['course_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'course_data_id')
    # ### end Alembic commands ###
