"""Add course_id to task

Revision ID: 8fbbcf0ca7da
Revises: 1973bad0fbd5
Create Date: 2023-12-05 18:25:57.920251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbbcf0ca7da'
down_revision: Union[str, None] = '1973bad0fbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'course_id')
    # ### end Alembic commands ###
