"""Try to fix course base

Revision ID: 9f2c696a8a7d
Revises: 60c7c58583b4
Create Date: 2023-11-26 21:37:50.579729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2c696a8a7d'
down_revision: Union[str, None] = '60c7c58583b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_data',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_data',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
