"""Add forgein keys

Revision ID: a48002c35df6
Revises: c54864a95d4c
Create Date: 2023-12-06 16:16:59.417771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48002c35df6'
down_revision: Union[str, None] = 'c54864a95d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classinvites', sa.Column('class_id', sa.Integer(), nullable=False))
    op.add_column('classinvites', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classinvites', 'classrooms', ['class_id'], ['id'])
    op.create_foreign_key(None, 'classinvites', 'user', ['creator_id'], ['id'])
    op.add_column('classrooms', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classrooms', 'user', ['owner_id'], ['id'])
    op.add_column('courses', sa.Column('course_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'courses_data', ['course_data_id'], ['id'])
    op.add_column('courses_data', sa.Column('modules', sa.JSON(), nullable=True))
    op.add_column('courses_data', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses_data', 'courses', ['course_id'], ['id'])
    op.add_column('modules', sa.Column('tasks', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('modules', sa.Column('course_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'courses_data', ['course_data_id'], ['id'])
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    op.add_column('task', sa.Column('module_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'task', 'modules', ['module_id'], ['id'])
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'course_id')
    op.drop_column('task', 'module_id')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'course_data_id')
    op.drop_column('modules', 'course_id')
    op.drop_column('modules', 'tasks')
    op.drop_constraint(None, 'courses_data', type_='foreignkey')
    op.drop_column('courses_data', 'course_id')
    op.drop_column('courses_data', 'modules')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'course_data_id')
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'owner_id')
    op.drop_constraint(None, 'classinvites', type_='foreignkey')
    op.drop_constraint(None, 'classinvites', type_='foreignkey')
    op.drop_column('classinvites', 'creator_id')
    op.drop_column('classinvites', 'class_id')
    # ### end Alembic commands ###
