"""Initital revision

Revision ID: c54864a95d4c
Revises: 
Create Date: 2023-12-06 16:15:56.369209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54864a95d4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classinvites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('works_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invites_last', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'invite_code')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('admins', sa.JSON(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('optins', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ico_url', sa.String(), nullable=False),
    sa.Column('teachers_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('passing_id', sa.JSON(), nullable=True),
    sa.Column('passed_id', sa.JSON(), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tasks_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('tests_type', sa.Integer(), nullable=True),
    sa.Column('simple_test_data', sa.JSON(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('solution_for_testing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('changed_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('ico_url', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('roles')
    op.drop_table('modules')
    op.drop_table('lessons')
    op.drop_table('courses_data')
    op.drop_table('courses')
    op.drop_table('classrooms')
    op.drop_table('classinvites')
    # ### end Alembic commands ###
