"""Change relationship at course 2

Revision ID: e6b51273ec37
Revises: f0f56d150d7e
Create Date: 2023-11-28 20:09:04.142624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b51273ec37'
down_revision: Union[str, None] = 'f0f56d150d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_data_course_id_fkey', 'courses_data', type_='foreignkey')
    op.drop_column('courses_data', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses_data', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('courses_data_course_id_fkey', 'courses_data', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
