"""Try to fix course base 2

Revision ID: f0f56d150d7e
Revises: 0da4d7e0c2cf
Create Date: 2023-11-28 17:33:15.064446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f56d150d7e'
down_revision: Union[str, None] = '0da4d7e0c2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
