"""Add solutions.priority

Revision ID: fea4e20fdcf0
Revises: 6ae9ea487697
Create Date: 2023-12-14 22:05:26.499741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea4e20fdcf0'
down_revision: Union[str, None] = '6ae9ea487697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'priority')
    # ### end Alembic commands ###
