name: Build and Test React Application

on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.0.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn ci and build
        run: |
          cd frontend;
          yarn install -D
          yarn build