name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "base"
      SECRET: "secret"
      SECRET_MANAGER: "secret2"
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin_pgadmin4"
    with:
      compose-file: "./docker-compose.yml"
      # down-flags: "--volumes"
      # services: |
      #   postgres
      #   backend
      #   frontend
      #   nginx