name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '40 14 * * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v3
    - name: Create .env file
      run: cp ./.env.example ./.env

    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Build the Docker image
      run: |
        sudo docker-compose -f ./docker-compose.yml up --build --abort-on-container-exit --exit-code-from service-test
      