name: Docker Image CI

on: [push]
env:
  FULLCHAIN_PEM: ${{ secrets.FULLCHAIN_PEM }}
  PRIVKEY_PEM: ${{ secrets.PRIVKEY_PEM }}
  CERT_PEM: ${{ secrets.CERT_PEM }}
  CHAIN_PEM: ${{ secrets.CHAIN_PEM }}

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com/xiver-org/testing-system/settings/environments/989119136
    
    steps:
    - uses: actions/checkout@v3
    - name: Create .env file
      run: cp ./.env.example ./.env

    - name: Key preparation
      run: |
        mkdir ./nginx/SSL
        echo ${FULLCHAIN_PEM} > ./nginx/SSL/fullchain.pem
        echo ${PRIVKEY_PEM} > ./nginx/SSL/privkey.pem
        echo ${CERT_PEM} > ./nginx/SSL/cert.pem
        echo ${CHAIN_PEM} > ./nginx/SSL/chain.pem

    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
    - name: Build the Docker image
      run: |
        sudo docker-compose -f ./docker-compose.yml up --build --abort-on-container-exit --exit-code-from service-test
      