name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "base"
      SECRET: "secret"
      SECRET_MANAGER: "secret2"
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin_pgadmin4"
    steps:
    - name: Create .env file
      run: touch .env

    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
    - name: Build the Docker image
      run: |
        sudo docker-compose -f ./docker-compose.yml up --build
      