name: Linting

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ruff
      run: pip install ruff

    - name: Ruff
      run: ruff .
