name: Linting

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: cd backend; poetry install --with dev && poetry shell

    - name: Ruff
      run: poetry run ruff .
